// Copyright 2023 Redglyph
//
// Integration tests: tests that all the functionalities are accessible and work as expected.

#![cfg(test)]

mod listener {
    use std::collections::HashMap;
    use rlexer::dfa::TokenId;
    use rlexer::grammar::{Symbol, VarId};
    use rlexer::parser::{Listener, Parser};
    use rlexer::symbol_table::SymbolTable;

    // Code generated by rparser -------------------------------------

    const SYMBOLS_T: [(&str, Option<&str>); 8] = [("PLUS", Some("+")), ("MINUS", Some("-")), ("MUL", Some("*")), ("DIV", Some("/")), ("LPAREN", Some("(")), ("RPAREN", Some(")")), ("N", None), ("I", None)];
    const SYMBOLS_NT: [&str; 5] = ["E", "T", "F", "E_1", "T_1"];
    const SYMBOLS_NAMES: [(&str, VarId); 2] = [("E_1", 3), ("T_1", 4)];
    const PARSING_FACTORS: [(VarId, &[Symbol]); 11] = [(0, &[Symbol::NT(1), Symbol::NT(3)]), (1, &[Symbol::NT(2), Symbol::NT(4)]), (2, &[Symbol::T(4), Symbol::NT(0), Symbol::T(5)]), (2, &[Symbol::T(6)]), (2, &[Symbol::T(7)]), (3, &[Symbol::T(0), Symbol::NT(1), Symbol::NT(3)]), (3, &[Symbol::T(1), Symbol::NT(1), Symbol::NT(3)]), (3, &[Symbol::Empty]), (4, &[Symbol::T(2), Symbol::NT(2), Symbol::NT(4)]), (4, &[Symbol::T(3), Symbol::NT(2), Symbol::NT(4)]), (4, &[Symbol::Empty])];
    const PARSING_TABLE: [VarId; 45] = [11, 11, 11, 11, 0, 11, 0, 0, 11, 11, 11, 11, 11, 1, 11, 1, 1, 11, 11, 11, 11, 11, 2, 11, 3, 4, 11, 5, 6, 11, 11, 11, 7, 11, 11, 7, 10, 10, 8, 9, 11, 10, 11, 11, 10];
    const START_SYMBOL: VarId = 0;

    pub(super) fn build_parser() -> Parser {
        let mut symbol_table = SymbolTable::new();
        symbol_table.extend_terminals(SYMBOLS_T.into_iter().map(|(s, os)| (s.to_string(), os.map(|s| s.to_string()))));
        symbol_table.extend_non_terminals(SYMBOLS_NT.into_iter().map(|s| s.to_string()));
        symbol_table.extend_names(SYMBOLS_NAMES.into_iter().map(|(s, v)| (s.to_string(), v)));
        let factors: Vec<(VarId, Vec<Symbol>)> = PARSING_FACTORS.into_iter().map(|(v, s)| (v, s.to_vec())).collect();
        let table: Vec<VarId> = PARSING_TABLE.into();
        let parsing_table = rlexer::grammar::LLParsingTable {
            num_nt: 5,
            num_t: 9,
            factors,
            table
        };
        Parser::new(parsing_table, symbol_table, START_SYMBOL)
    }

    pub trait ExprListenerTrait {
        fn visit_e(&mut self) {}
        fn visit_t(&mut self) {}
        fn visit_f(&mut self) {}
        fn visit_e_1(&mut self) {}
        fn visit_t_1(&mut self) {}
    }

    struct ListenerWrapper<T>(T);

    impl<T: ExprListenerTrait> ListenerWrapper<T> {
        pub fn new(listener: T) -> Self {
            Self(listener)
        }

        pub fn listener(self) -> T {
            self.0
        }
    }

    // `Parser::parse_stream_hook` requires a type implementing `Listener`, but we can only implement
    // `Listener` on a local type, not as a blanket implementation on any type implementing `ExprListenerTrait`,
    // so we must have the `ListenerWrapper` wrapper type above.
    impl<T: ExprListenerTrait> Listener for ListenerWrapper<T> {
        fn switch(&mut self, nt: VarId) {
            match nt {
                0 => self.0.visit_e(),
                1 => self.0.visit_t(),
                2 => self.0.visit_f(),
                3 => self.0.visit_e_1(),
                4 => self.0.visit_t_1(),
                _ => panic!("unexpected nt exit value: {nt}")
            }
        }
    }

    // User code -----------------------------------------------------

    struct TestListener {
        result: Vec<String>,
    }

    impl TestListener {
        pub fn new() -> Self {
            Self { result: Vec::new() }
        }
    }

    impl ExprListenerTrait for TestListener {
        fn visit_e(&mut self) {
            println!("E");
            self.result.push("E".to_string());
        }

        fn visit_t(&mut self) {
            println!("T");
            self.result.push("T".to_string());
        }

        fn visit_f(&mut self) {
            println!("F");
            self.result.push("F".to_string());
        }

        // we're not interested in visit_e_1

        fn visit_t_1(&mut self) {
            println!("T_1");
            self.result.push("T_1".to_string());
        }
    }

    #[test]
    fn parser_parse_stream_hook() {
        let tests = vec![
            ("I+N*I", true, vec!["F", "T_1", "T", "F", "F", "T_1", "T_1", "T", "E"]),
            ("I*(N+N)", true, vec!["F", "F", "T_1", "T", "F", "T_1", "T", "E", "F", "T_1", "T_1", "T", "E"]),
        ];
        const VERBOSE: bool = true;
        let mut parser = build_parser();

        // The lexer provides the required stream, so this isn't necessary in a real case:
        let mut symb_table = SymbolTable::new();
        symb_table.extend_terminals(SYMBOLS_T.iter().map(|(s, ss)| (s.to_string(), ss.map(|s| s.to_string()))));
        let symbols = (0..SYMBOLS_T.len() as TokenId)
            .map(|t| Symbol::T(t))
            .map(|s| (s.to_str(Some(&symb_table)), s))
            .collect::<HashMap<_, _>>();
        for (test_id, (input, expected_success, expected_result)) in tests.into_iter().enumerate() {
            if VERBOSE { println!("{:=<80}\ninput '{input}'", ""); }
            let stream = input.chars().into_iter().filter_map(|c| {
                if c.is_ascii_whitespace() {
                    None
                } else {
                    let c_str = c.to_string();
                    if let Some(s) = symbols.get(&c_str) {
                        // println!("stream: '{}' -> sym!({})", c, symbol_to_macro(s));
                        Some((*s, c_str))
                    } else {
                        panic!("unrecognized test input '{c}' in test {test_id}, input {input}");
                    }
                }
            });

            // User code under test ------------------------------

            let listener = TestListener::new();
            let mut wrapper = ListenerWrapper::new(listener);
            let success = match parser.parse_stream_hook(&mut wrapper, stream) {
                Ok(_) => {
                    if VERBOSE { println!("parsing completed successfully"); }
                    true
                }
                Err(e) => {
                    if VERBOSE { println!("parsing failed: {e}"); }
                    false
                }
            };
            let listener = wrapper.listener();

            // ---------------------------------------------------

            assert_eq!(success, expected_success, "test {test_id} failed for input {input}");
            if VERBOSE { println!("listener data: {}", listener.result.join(" -> ")); }
            assert_eq!(listener.result, expected_result);
        }
    }
}
