[package]
name = "watcher"
version = "0.1.0"
description = "example of watcher with low latency and infinite input"
edition = "2024"
authors.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# enable this feature to get a lower latency when parsing lines:
# features = ["delay_stream_interception"]
lexigram-core = { path = "../../lexigram-core", version = "0.9.1" }

[lints]
workspace = true
