// Copyright (c) 2025 Redglyph (@gmail.com). All Rights Reserved.

#![cfg(test)]
#![allow(non_camel_case_types)]

#[allow(unused)]
mod parser_gen {

    #[test]
    fn test_source_code_manual() {
        let _parser = source_code_manual::build_parser();
    }

    // This is generated by `lexigram::parsergen::gen_integration::write_source_code_from_ll1`, with `build_prs(13)`
    mod source_code_manual {
        // -------------------------------------------------------------------------
        // [write_source_code_from_ll1]

        use lexigram::{grammar::{FactorId, ProdFactor, Symbol, VarId}, parser::{OpCode, Parser}, symbol_table::SymbolTable};

        const PARSER_NUM_T: usize = 10;
        const PARSER_NUM_NT: usize = 3;
        const SYMBOLS_T: [(&str, Option<&str>); PARSER_NUM_T] = [("SUB", Some("-")), ("ADD", Some("+")), ("DIV", Some("/")), ("MUL", Some("*")), ("LPAREN", Some("(")), ("RPAREN", Some(")")), ("N", None), ("I", None), ("EXP", Some("^")), ("DUM", Some(":"))];
        const SYMBOLS_NT: [&str; PARSER_NUM_NT] = ["E", "F", "E_1"];
        const PARSING_FACTORS: [(VarId, &[Symbol]); 11] = [(0, &[Symbol::NT(1), Symbol::NT(2)]), (1, &[Symbol::T(4), Symbol::NT(0), Symbol::T(5)]), (1, &[Symbol::T(6)]), (1, &[Symbol::T(7)]), (2, &[Symbol::T(9), Symbol::NT(1), Symbol::NT(2)]), (2, &[Symbol::T(8), Symbol::NT(1), Symbol::NT(2)]), (2, &[Symbol::T(2), Symbol::NT(1), Symbol::NT(2)]), (2, &[Symbol::T(3), Symbol::NT(1), Symbol::NT(2)]), (2, &[Symbol::T(0), Symbol::NT(1), Symbol::NT(2)]), (2, &[Symbol::T(1), Symbol::NT(1), Symbol::NT(2)]), (2, &[Symbol::Empty])];
        const PARSING_TABLE: [FactorId; 33] = [11, 11, 11, 11, 0, 12, 0, 0, 11, 11, 12, 12, 12, 12, 12, 1, 12, 2, 3, 12, 12, 12, 8, 9, 6, 7, 11, 10, 11, 11, 5, 4, 10];
        const FLAGS: [u32; 3] = [1536, 0, 142];
        const PARENT: [Option<VarId>; 3] = [None, None, Some(0)];
        const OPCODES: [&[OpCode]; 11] = [&[OpCode::NT(2), OpCode::Exit(0), OpCode::NT(1)], &[OpCode::Exit(1), OpCode::T(5), OpCode::NT(0), OpCode::T(4)], &[OpCode::Exit(2), OpCode::T(6)], &[OpCode::Exit(3), OpCode::T(7)], &[OpCode::Loop(2), OpCode::Exit(4), OpCode::NT(1), OpCode::T(9)], &[OpCode::Loop(2), OpCode::Exit(5), OpCode::NT(1), OpCode::T(8)], &[OpCode::Loop(2), OpCode::Exit(6), OpCode::NT(1), OpCode::T(2)], &[OpCode::Loop(2), OpCode::Exit(7), OpCode::NT(1), OpCode::T(3)], &[OpCode::Loop(2), OpCode::Exit(8), OpCode::NT(1), OpCode::T(0)], &[OpCode::Loop(2), OpCode::Exit(9), OpCode::NT(1), OpCode::T(1)], &[OpCode::Exit(10)]];
        const START_SYMBOL: VarId = 0;

        pub fn build_parser() -> Parser {
            let mut symbol_table = SymbolTable::new();
            symbol_table.extend_terminals(SYMBOLS_T.into_iter().map(|(s, os)| (s.to_string(), os.map(|s| s.to_string()))));
            symbol_table.extend_non_terminals(SYMBOLS_NT.into_iter().map(|s| s.to_string()));
            let factors: Vec<(VarId, ProdFactor)> = PARSING_FACTORS.into_iter().map(|(v, s)| (v, ProdFactor::new(s.to_vec()))).collect();
            let table: Vec<FactorId> = PARSING_TABLE.into();
            let parsing_table = lexigram::grammar::LLParsingTable {
                num_nt: PARSER_NUM_NT,
                num_t: PARSER_NUM_T + 1,
                factors,
                table,
                flags: FLAGS.into(),
                parent: PARENT.into(),
            };
            Parser::new(parsing_table, symbol_table, OPCODES.into_iter().map(|strip| strip.to_vec()).collect(), START_SYMBOL)
        }

        // [write_source_code_from_ll1]
        // -------------------------------------------------------------------------
    }
}

#[allow(unused)]
mod listener1 {

    // -------------------------------------------------------------------------
    // [write_source_code_for_integration_listener1]

    use lexigram::{grammar::{FactorId, ProdFactor, Symbol, VarId}, parser::{OpCode, Parser}, symbol_table::SymbolTable};

    const PARSER_NUM_T: usize = 8;
    const PARSER_NUM_NT: usize = 5;
    const SYMBOLS_T: [(&str, Option<&str>); PARSER_NUM_T] = [("SUB", Some("-")), ("ADD", Some("+")), ("DIV", Some("/")), ("MUL", Some("*")), ("LPAREN", Some("(")), ("RPAREN", Some(")")), ("N", None), ("I", None)];
    const SYMBOLS_NT: [&str; PARSER_NUM_NT] = ["E", "T", "F", "E_1", "T_1"];
    const PARSING_FACTORS: [(VarId, &[Symbol]); 11] = [(0, &[Symbol::NT(1), Symbol::NT(3)]), (1, &[Symbol::NT(2), Symbol::NT(4)]), (2, &[Symbol::T(4), Symbol::NT(0), Symbol::T(5)]), (2, &[Symbol::T(6)]), (2, &[Symbol::T(7)]), (3, &[Symbol::T(0), Symbol::NT(1), Symbol::NT(3)]), (3, &[Symbol::T(1), Symbol::NT(1), Symbol::NT(3)]), (3, &[Symbol::Empty]), (4, &[Symbol::T(2), Symbol::NT(2), Symbol::NT(4)]), (4, &[Symbol::T(3), Symbol::NT(2), Symbol::NT(4)]), (4, &[Symbol::Empty])];
    const PARSING_TABLE: [FactorId; 45] = [11, 11, 11, 11, 0, 12, 0, 0, 12, 12, 12, 11, 11, 1, 12, 1, 1, 12, 12, 12, 12, 12, 2, 12, 3, 4, 12, 5, 6, 11, 11, 11, 7, 11, 11, 7, 10, 10, 8, 9, 11, 10, 11, 11, 10];
    const FLAGS: [u32; 5] = [512, 512, 0, 4, 4];
    const PARENT: [Option<VarId>; 5] = [None, None, None, Some(0), Some(1)];
    const OPCODES: [&[OpCode]; 11] = [&[OpCode::NT(3), OpCode::Exit(0), OpCode::NT(1)], &[OpCode::NT(4), OpCode::Exit(1), OpCode::NT(2)], &[OpCode::Exit(2), OpCode::T(5), OpCode::NT(0), OpCode::T(4)], &[OpCode::Exit(3), OpCode::T(6)], &[OpCode::Exit(4), OpCode::T(7)], &[OpCode::Loop(3), OpCode::Exit(5), OpCode::NT(1), OpCode::T(0)], &[OpCode::Loop(3), OpCode::Exit(6), OpCode::NT(1), OpCode::T(1)], &[OpCode::Exit(7)], &[OpCode::Loop(4), OpCode::Exit(8), OpCode::NT(2), OpCode::T(2)], &[OpCode::Loop(4), OpCode::Exit(9), OpCode::NT(2), OpCode::T(3)], &[OpCode::Exit(10)]];
    const START_SYMBOL: VarId = 0;

    pub fn build_parser() -> Parser {
        let mut symbol_table = SymbolTable::new();
        symbol_table.extend_terminals(SYMBOLS_T.into_iter().map(|(s, os)| (s.to_string(), os.map(|s| s.to_string()))));
        symbol_table.extend_non_terminals(SYMBOLS_NT.into_iter().map(|s| s.to_string()));
        let factors: Vec<(VarId, ProdFactor)> = PARSING_FACTORS.into_iter().map(|(v, s)| (v, ProdFactor::new(s.to_vec()))).collect();
        let table: Vec<FactorId> = PARSING_TABLE.into();
        let parsing_table = lexigram::grammar::LLParsingTable {
            num_nt: PARSER_NUM_NT,
            num_t: PARSER_NUM_T + 1,
            factors,
            table,
            flags: FLAGS.into(),
            parent: PARENT.into(),
        };
        Parser::new(parsing_table, symbol_table, OPCODES.into_iter().map(|strip| strip.to_vec()).collect(), START_SYMBOL)
    }

    // [write_source_code_for_integration_listener1]
    // -------------------------------------------------------------------------
}

// ---------------------------------------------------------------------------------------------
// General helper traits

#[allow(unused)]
mod listener2 {
    use std::collections::HashMap;
    use std::str::FromStr;
    use iter_index::IndexerIterator;
    use lexigram::dfa::TokenId;
    use lexigram::parser::{Call, ListenerWrapper};
    use lexigram::CollectJoin;
    use lexigram::lexer::CaretCol;
    use lexigram::log::{BufLog, Logger};

    // -------------------------------------------------------------------------
    // [write_source_code_for_integration_listener2]

    use lexigram::{grammar::{FactorId, ProdFactor, Symbol, VarId}, parser::{OpCode, Parser}, symbol_table::SymbolTable};

    const PARSER_NUM_T: usize = 10;
    const PARSER_NUM_NT: usize = 4;
    const SYMBOLS_T: [(&str, Option<&str>); PARSER_NUM_T] = [("ABS", Some("abs")), ("NEG", Some("-")), ("EXP", Some("^")), ("MUL", Some("*")), ("ADD", Some("+")), ("LPAREN", Some("(")), ("RPAREN", Some(")")), ("NUM", None), ("ID", None), ("PRIME", Some("'"))];
    const SYMBOLS_NT: [&str; PARSER_NUM_NT] = ["E", "F", "E_1", "E_2"];
    const PARSING_FACTORS: [(VarId, &[Symbol]); 12] = [(0, &[Symbol::NT(2), Symbol::NT(3)]), (1, &[Symbol::T(5), Symbol::NT(0), Symbol::T(6)]), (1, &[Symbol::T(7)]), (1, &[Symbol::T(8)]), (2, &[Symbol::T(0), Symbol::NT(2), Symbol::NT(3)]), (2, &[Symbol::T(1), Symbol::NT(2), Symbol::NT(3)]), (2, &[Symbol::NT(1)]), (3, &[Symbol::T(9), Symbol::NT(3)]), (3, &[Symbol::T(2), Symbol::NT(2), Symbol::NT(3)]), (3, &[Symbol::T(3), Symbol::NT(2), Symbol::NT(3)]), (3, &[Symbol::T(4), Symbol::NT(2), Symbol::NT(3)]), (3, &[Symbol::Empty])];
    const PARSING_TABLE: [FactorId; 44] = [0, 0, 12, 12, 12, 0, 13, 0, 0, 12, 13, 12, 12, 13, 13, 13, 1, 13, 2, 3, 13, 13, 4, 5, 13, 13, 13, 6, 13, 6, 6, 13, 13, 12, 12, 8, 9, 10, 12, 11, 12, 12, 7, 11];
    const FLAGS: [u32; 4] = [1536, 0, 16, 142];
    const PARENT: [Option<VarId>; 4] = [None, None, Some(0), Some(0)];
    const OPCODES: [&[OpCode]; 12] = [&[OpCode::NT(3), OpCode::Exit(0), OpCode::NT(2)], &[OpCode::Exit(1), OpCode::T(6), OpCode::NT(0), OpCode::T(5)], &[OpCode::Exit(2), OpCode::T(7)], &[OpCode::Exit(3), OpCode::T(8)], &[OpCode::Loop(3), OpCode::Exit(4), OpCode::Loop(2), OpCode::T(0)], &[OpCode::Loop(3), OpCode::Exit(5), OpCode::Loop(2), OpCode::T(1)], &[OpCode::Exit(6), OpCode::NT(1)], &[OpCode::Loop(3), OpCode::Exit(7), OpCode::T(9)], &[OpCode::Loop(3), OpCode::Exit(8), OpCode::NT(2), OpCode::T(2)], &[OpCode::Loop(3), OpCode::Exit(9), OpCode::NT(2), OpCode::T(3)], &[OpCode::Loop(3), OpCode::Exit(10), OpCode::NT(2), OpCode::T(4)], &[OpCode::Exit(11)]];
    const START_SYMBOL: VarId = 0;

    pub fn build_parser() -> Parser {
        let mut symbol_table = SymbolTable::new();
        symbol_table.extend_terminals(SYMBOLS_T.into_iter().map(|(s, os)| (s.to_string(), os.map(|s| s.to_string()))));
        symbol_table.extend_non_terminals(SYMBOLS_NT.into_iter().map(|s| s.to_string()));
        let factors: Vec<(VarId, ProdFactor)> = PARSING_FACTORS.into_iter().map(|(v, s)| (v, ProdFactor::new(s.to_vec()))).collect();
        let table: Vec<FactorId> = PARSING_TABLE.into();
        let parsing_table = lexigram::grammar::LLParsingTable {
            num_nt: PARSER_NUM_NT,
            num_t: PARSER_NUM_T + 1,
            factors,
            table,
            flags: FLAGS.into(),
            parent: PARENT.into(),
        };
        Parser::new(parsing_table, symbol_table, OPCODES.into_iter().map(|strip| strip.to_vec()).collect(), START_SYMBOL)
    }

    // [write_source_code_for_integration_listener2]
    // -------------------------------------------------------------------------

    // E -> E : E | E ^ E | E / E | E * E | E - E | E + E | F
    // F -> ( E ) | NUM | ID
    //
    // E -> F E_1
    // F -> ( E ) | N | I
    // E_1 -> : F E_1 | ^ F E_1 | / F E_1 | * F E_1 | - F E_1 | + F E_1 | ε
    //
    //  0: E -> F E_1     | ►E_1 ◄0 ►F   | F
    //  1: F -> ( E )     | ◄1 ) ►E (    | E
    //  2: F -> N         | ◄2 N!        | N
    //  3: F -> I         | ◄3 I!        | I
    //  4: E_1 -> : F E_1 | ●E_1 ◄4 ►F : | E F
    //  5: E_1 -> ^ F E_1 | ●E_1 ◄5 ►F ^ | E F
    //  6: E_1 -> / F E_1 | ●E_1 ◄6 ►F / | E F
    //  7: E_1 -> * F E_1 | ●E_1 ◄7 ►F * | E F
    //  8: E_1 -> - F E_1 | ●E_1 ◄8 ►F - | E F
    //  9: E_1 -> + F E_1 | ●E_1 ◄9 ►F + | E F
    // 10: E_1 -> ε       | ◄10          |
    //
    //
    // NT flags:
    //  - E: parent_left_rec | parent_amb (1536)
    //  - E_1: child_left_rec | child_amb (12)
    // parents:
    //  - E_1 -> E

    pub enum CtxE {
        Dum { e: [SynE; 2] },
        Exp { e: [SynE; 2] },
        Div { e: [SynE; 2] },
        Mul { e: [SynE; 2] },
        Sub { e: [SynE; 2] },
        Add  { e: [SynE; 2] },
        F { f: SynE } }
    pub enum CtxF { E { e: SynE }, Num(String), Id(String) }

    enum SynValue { F(SynE), E_1(SynE), E(SynE) }

    impl std::fmt::Debug for SynValue {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            match self {
                SynValue::F(e) => write!(f, "E({})", syn_e_str(e)),
                SynValue::E_1(e) => write!(f, "E_1({})", syn_e_str(e)),
                SynValue::E(e) => write!(f, "E({})", syn_e_str(e)),
            }
        }
    }

    impl SynValue {
        fn get_e(self) -> SynE {
            if let SynValue::E(val) = self { val } else { panic!() }
        }
        fn get_e_1(self) -> SynE {
            if let SynValue::E_1(val) = self { val } else { panic!() }
        }
        fn get_f(self) -> SynE {
            if let SynValue::F(val) = self { val } else { panic!() }
        }
    }

    #[derive(Debug, PartialEq)]
    enum AsmE { E, E_1_Dum, E_1_Exp, E_1_Div, E_1_Mul, E_1_Sub, E_1_Add, E_1_Empty }

    struct AsmItem {
        val: SynE,
        ty: AsmE,
    }

    impl std::fmt::Debug for AsmItem {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            let e = &self.val;
            match self.ty {
                AsmE::E => write!(f, "E({})", syn_e_str(e)),
                AsmE::E_1_Dum => write!(f, "E_1(: {})", syn_e_str(e)),
                AsmE::E_1_Exp => write!(f, "E_1(^ {})", syn_e_str(e)),
                AsmE::E_1_Div => write!(f, "E_1(/ {})", syn_e_str(e)),
                AsmE::E_1_Mul => write!(f, "E_1(* {})", syn_e_str(e)),
                AsmE::E_1_Sub => write!(f, "E_1(- {})", syn_e_str(e)),
                AsmE::E_1_Add => write!(f, "E_1(+ {})", syn_e_str(e)),
                AsmE::E_1_Empty => write!(f, "E_1(ε)")
            }
        }
    }

    const LEFT_ASSOC_DUM: bool = true;
    const LEFT_ASSOC_EXP: bool = false;
    const LEFT_ASSOC_DIV: bool = true;
    const LEFT_ASSOC_MUL: bool = true;
    const LEFT_ASSOC_SUB: bool = true;
    const LEFT_ASSOC_ADD: bool = true;
    const LEFT_ASSOC_EMPTY: bool = true; // don't care as long as its priority is high enough to fold

    impl AsmE {
        fn is_left_assoc(&self) -> bool {
            match self {
                AsmE::E         => false,
                AsmE::E_1_Dum   => LEFT_ASSOC_DUM,
                AsmE::E_1_Exp   => LEFT_ASSOC_EXP,
                AsmE::E_1_Div   => LEFT_ASSOC_DIV,
                AsmE::E_1_Mul   => LEFT_ASSOC_MUL,
                AsmE::E_1_Sub   => LEFT_ASSOC_SUB,
                AsmE::E_1_Add   => LEFT_ASSOC_ADD,
                AsmE::E_1_Empty => LEFT_ASSOC_EMPTY,
            }
        }
    }

    const PRIORITY_MIN: u16 = 0;
    const PRIORITY_ADD: u16 = 1;
    const PRIORITY_SUB: u16 = 2;
    const PRIORITY_MUL: u16 = 3;
    const PRIORITY_DIV: u16 = 4;
    const PRIORITY_EXP: u16 = 5;
    const PRIORITY_DUM: u16 = 6;
    const PRIORITY_MAX: u16 = u16::MAX;
    const PRIORITY_EMPTY: u16 = PRIORITY_MIN;

    pub trait ExprListener { 
        fn check_abort_request(&self) -> bool { false }
        fn get_mut_log(&mut self) -> &mut impl Logger;        
        fn init_e(&mut self) {}
        fn init_f(&mut self, _factor_id: VarId) {}
        fn exit_e(&mut self, _ctx: CtxE) -> SynE;
        fn exit_f(&mut self, _ctx: CtxF) -> SynE;
    }

    // `Parser::parse_stream_hook` requires a type implementing `Listener`, but we can only implement
    // `Listener` on a local type, not as a blanket implementation on any type implementing `ExprListenerTrait`,
    // so we must have the `Wrapper` wrapper type above.
    pub struct Wrapper<T> {
        verbose: bool,
        listener: T,
        stack: Vec<SynValue>,
        asm_stack: Vec<(AsmItem, u16, bool)>, // item, priority, is_left_assoc
        max_stack: usize,
        max_asm_stack: usize,
        stack_t: Vec<String>
    }

    impl<T: ExprListener> Wrapper<T> {
        pub fn new(listener: T, verbose: bool) -> Self {
            Wrapper { verbose, listener, stack: Vec::new(), asm_stack: Vec::new(), max_stack: 0, max_asm_stack: 0, stack_t: Vec::new() }
        }

        pub fn listener(self) -> T {
            self.listener
        }
    }

    impl<T: ExprListener> ListenerWrapper for Wrapper<T> {
        fn switch(&mut self, call: Call, nt: VarId, factor_id: FactorId, t_data: Option<Vec<String>>) {
            if let Some(mut t_data) = t_data {
                self.stack_t.append(&mut t_data);
            }
            match call {
                Call::Enter => {
                    match nt {
                        0 => self.init_e(),
                        1 => self.listener.init_f(factor_id),
                        2 => {}
                        _ => panic!("unexpected exit nt: {nt}")
                    }
                }
                Call::Loop => {}
                Call::Exit => {
                    if self.verbose && nt == 2 {
                        println!("◄ {}", factor_str(factor_id, true));
                    }
                    match factor_id {
                        0 => self.init_e_1(),                                       //  0: E -> F E_1     | ►E_1 ◄0 ►F   | F
                        1 => self.exit_f1(),                                        //  1: F -> ( E )     | ◄1 ) ►E (    | E
                        2 => self.exit_f2(),                                        //  2: F -> N         | ◄2 N!        | N
                        3 => self.exit_f3(),                                        //  3: F -> I         | ◄3 I!        | I
                        4 => self.asm_e_1(factor_id, PRIORITY_DUM, LEFT_ASSOC_DUM), //  4: E_1 -> : F E_1 | ●E_1 ◄4 ►F : | E F
                        5 => self.asm_e_1(factor_id, PRIORITY_EXP, LEFT_ASSOC_EXP), //  5: E_1 -> ^ F E_1 | ●E_1 ◄5 ►F ^ | E F
                        6 => self.asm_e_1(factor_id, PRIORITY_DIV, LEFT_ASSOC_DIV), //  6: E_1 -> / F E_1 | ●E_1 ◄6 ►F / | E F
                        7 => self.asm_e_1(factor_id, PRIORITY_MUL, LEFT_ASSOC_MUL), //  7: E_1 -> * F E_1 | ●E_1 ◄7 ►F * | E F
                        8 => self.asm_e_1(factor_id, PRIORITY_SUB, LEFT_ASSOC_SUB), //  8: E_1 -> - F E_1 | ●E_1 ◄8 ►F - | E F
                        9 => self.asm_e_1(factor_id, PRIORITY_ADD, LEFT_ASSOC_ADD), //  9: E_1 -> + F E_1 | ●E_1 ◄9 ►F + | E F
                        10 => self.exit_e(),                                        // 10: E_1 -> ε       | ◄10          |
                        _ => panic!("unexpected exit factor id: {factor_id}")
                    }
                }
                Call::End => {
                    self.exit();
                }
            }
            self.max_stack = std::cmp::max(self.max_stack, self.stack.len());
            self.max_asm_stack = std::cmp::max(self.max_asm_stack, self.asm_stack.len());
            if self.verbose {
                println!("> stack:     {}", self.stack.iter().map(|it| format!("{it:?}")).join(", "));
                println!("> asm_stack: {}", self.asm_stack.iter().map(|(it, p, l)| format!("{it:?}/{p}/{}", if *l { "L" } else { "R" })).join(", "));
            }
        }

        fn check_abort_request(&self) -> bool {
            self.listener.check_abort_request()
        }
        
        fn get_mut_log(&mut self) -> &mut impl Logger {
            self.listener.get_mut_log()
        }
    }

    impl<T: ExprListener> Wrapper<T> {
        fn exit(&mut self) {
            // TODO:
        }

        fn fold_e_1(&mut self, priority: u16, mut is_left_assoc: bool) {
            // Folding the top two items while the priority of the top item is higher than the argument.
            // If left-associative, we allow folding items of the same priority, so we are sure that
            // the priority is always increasing towards the top of the stack. This allows us to fold
            // right- and left-associative items the same way (which we couldn't if two or more left-associative
            // items had the same priority).
            while self.asm_stack.len() > 1 && self.asm_stack.last().map(|(e, p, left)| e.ty != AsmE::E && (*p > priority || (*p == priority && is_left_assoc))).unwrap() {
                let (new, _, _) = self.asm_stack.pop().unwrap();
                let (top, _, _) = self.asm_stack.last_mut().unwrap();
                if self.verbose {
                    println!("- fold with priority {priority}/{}: {top:?} and {new:?}", if is_left_assoc { "L" } else { "R" });
                }
                match new.ty {
                    AsmE::E_1_Dum   => { top.val = self.listener.exit_e(CtxE::Dum { e: [top.val, new.val] }); }
                    AsmE::E_1_Exp   => { top.val = self.listener.exit_e(CtxE::Exp { e: [top.val, new.val] }); }
                    AsmE::E_1_Div   => { top.val = self.listener.exit_e(CtxE::Div { e: [top.val, new.val] }); }
                    AsmE::E_1_Mul   => { top.val = self.listener.exit_e(CtxE::Mul { e: [top.val, new.val] }); }
                    AsmE::E_1_Sub   => { top.val = self.listener.exit_e(CtxE::Sub { e: [top.val, new.val] }); }
                    AsmE::E_1_Add   => { top.val = self.listener.exit_e(CtxE::Add { e: [top.val, new.val] }); }
                    AsmE::E_1_Empty => { },
                    // we must never pop AsmE::E here, so we must ignore its case
                    _ => panic!()
                }
                if self.verbose {
                    println!("-> {top:?}");
                }
                is_left_assoc = top.ty.is_left_assoc();
            }
        }

        fn init_e(&mut self) {
            // stopper for this expression (PRIORITY_MIN and right-associativity means it will never be merged)
            self.listener.init_e();
            self.asm_stack.push((AsmItem { val: None, ty: AsmE::E}, PRIORITY_MIN, false));
        }

        fn init_e_1(&mut self) {
            // F of E -> F E_1 is now on the stack => attach it
            let new_f = self.stack.pop().unwrap().get_f();
            // child_amb, so promoting the value:
            let mut new_e = self.listener.exit_e(CtxE::F { f: new_f });
            let top = &mut self.asm_stack.last_mut().unwrap().0;
            assert_eq!(top.ty, AsmE::E);
            assert_eq!(top.val, None);
            if self.verbose { println!("◄ 0, attach {} to E", syn_e_str(&new_e)); }
            top.val = new_e;
        }

        // left_rec/ambig, E : E | E ^ E | E / E | E * E | E - E | E + E | F
        // - 0: E -> F E_1
        fn exit_e(&mut self) {
            // child_amb e_1:
            self.fold_e_1(PRIORITY_MIN, false);
            let (e, _, _) = self.asm_stack.pop().expect("E should be on top of the stack");
            assert_eq!(e.ty, AsmE::E, "the top of the stack should be E instead of {e:?}");
            self.stack.push(SynValue::E(e.val));
        }

        // child_left_rec, child_amb
        fn asm_e_1(&mut self, factor_id: VarId, priority: u16, is_left_assoc: bool) {
            self.fold_e_1(priority, is_left_assoc);
            // child_amb, so promoting the value:
            let new_f = self.stack.pop().unwrap().get_f();
            let mut new_e = self.listener.exit_e(CtxE::F { f: new_f });
            let r = match factor_id {
                4 => AsmItem { val: new_e, ty: AsmE::E_1_Dum },
                5 => AsmItem { val: new_e, ty: AsmE::E_1_Exp },
                6 => AsmItem { val: new_e, ty: AsmE::E_1_Div },
                7 => AsmItem { val: new_e, ty: AsmE::E_1_Mul },
                8 => AsmItem { val: new_e, ty: AsmE::E_1_Sub },
                9 => AsmItem { val: new_e, ty: AsmE::E_1_Add },
                _ => panic!()
            };
            self.asm_stack.push((r, priority, is_left_assoc));
        }

        fn exit_f1(&mut self) {
            let ctx = CtxF::E { e: self.stack.pop().unwrap().get_e() };
            self.stack.push(SynValue::F(self.listener.exit_f(ctx)));
        }

        fn exit_f2(&mut self) {
            let ctx = CtxF::Num(self.stack_t.pop().unwrap());
            self.stack.push(SynValue::F(self.listener.exit_f(ctx)));
        }

        fn exit_f3(&mut self) {
            let ctx = CtxF::Id(self.stack_t.pop().unwrap());
            self.stack.push(SynValue::F(self.listener.exit_f(ctx)));
        }
    }

    // User code -----------------------------------------------------

    type SynE = Option<i64>;
    type SynF = Option<i64>;

    fn syn_e_str(e: &SynE) -> String {
        if let Some(v) = e {
            v.to_string()
        } else {
            "?".to_string()
        }
    }

    struct TestListener {
        vars: HashMap<String, i64>,
        result: Option<i64>,
        verbose: bool,
        log: BufLog
    }

    impl TestListener {
        pub fn new(verbose: bool) -> Self {
            Self { vars: HashMap::new(), result: None, verbose, log: BufLog::new() }
        }
    }

    fn factor_str(factor_id: VarId, nt: bool) -> String {
        match factor_id {
             0 => if nt { "E -> F E_1"     } else { "F E_1"   },
             1 => if nt { "F -> ( E )"     } else { "( E )"   },
             2 => if nt { "F -> N"         } else { "N"       },
             3 => if nt { "F -> I"         } else { "I"       },
             4 => if nt { "E_1 -> : F E_1" } else { ": F E_1" },
             5 => if nt { "E_1 -> ^ F E_1" } else { "^ F E_1" },
             6 => if nt { "E_1 -> / F E_1" } else { "/ F E_1" },
             7 => if nt { "E_1 -> * F E_1" } else { "* F E_1" },
             8 => if nt { "E_1 -> - F E_1" } else { "- F E_1" },
             9 => if nt { "E_1 -> + F E_1" } else { "+ F E_1" },
            10 => if nt { "E_1 -> ε"       } else { "ε"       },
            _ => panic!()
        }.to_string()
    }

    impl ExprListener for TestListener {
        fn get_mut_log(&mut self) -> &mut impl Logger {
            &mut self.log
        }

        fn init_e(&mut self) {
            if self.verbose {
                println!("► E");
            }
            self.result = None;
        }

        fn init_f(&mut self, factor_id: VarId) {
            if self.verbose { println!("► F -> {}", factor_str(factor_id, false)); }
        }

        fn exit_e(&mut self, ctx: CtxE) -> SynE {
            let value = match &ctx {
                CtxE::Dum { e } => {
                    if let [Some(e0), Some(e1)] = e {
                        Some(i64::max(*e0, *e1))
                    } else {
                        None
                    }
                }
                CtxE::Exp { e } => {
                    if let [Some(e0), Some(e1)] = e {
                        if *e1 <= u32::MAX as i64 {
                            e0.checked_pow(*e1 as u32)
                        } else {
                            None
                        }
                    } else {
                        None
                    }
                }
                CtxE::Div { e } => {
                    if let [Some(e0), Some(e1)] = e {
                        e0.checked_div(*e1)
                    } else {
                        None
                    }
                }
                CtxE::Mul { e } => {
                    if let [Some(e0), Some(e1)] = e {
                        e0.checked_mul(*e1)
                    } else {
                        None
                    }
                }
                CtxE::Sub { e } => {
                    if let [Some(e0), Some(e1)] = e {
                        e0.checked_sub(*e1)
                    } else {
                        None
                    }
                }
                CtxE::Add { e } => {
                    if let [Some(e0), Some(e1)] = e {
                        e0.checked_add(*e1)
                    } else {
                        None
                    }
                }
                CtxE::F { f } => *f,
            };
            if self.verbose {
                let output = match ctx {
                    CtxE::Dum { e } => format!("◄ E={:?} : {:?}={value:?}", e[0], e[1]),
                    CtxE::Exp { e } => format!("◄ E={:?} ^ {:?}={value:?}", e[0], e[1]),
                    CtxE::Div { e } => format!("◄ E={:?} / {:?}={value:?}", e[0], e[1]),
                    CtxE::Mul { e } => format!("◄ E={:?} * {:?}={value:?}", e[0], e[1]),
                    CtxE::Sub { e } => format!("◄ E={:?} - {:?}={value:?}", e[0], e[1]),
                    CtxE::Add { e } => format!("◄ E={:?} + {:?}={value:?}", e[0], e[1]),
                    CtxE::F { f } => format!("◄ E=F={value:?}"),
                };
                println!("{output}");
            }
            self.result = value;
            value
        }

        fn exit_f(&mut self, ctx: CtxF) -> SynE {
            let value = match &ctx {
                CtxF::E { e } => *e,
                CtxF::Num(s) => i64::from_str(s).ok(),
                CtxF::Id(s) => self.vars.get(s).cloned(),
            };
            if self.verbose {
                let output = match ctx {
                    CtxF::E { .. } => format!("◄ F=E={value:?}"),
                    CtxF::Num(n) => format!("◄ F=NUM #{n}={value:?}"),
                    CtxF::Id(i) => format!("◄ F=ID '{i}'={value:?}"),
                };
                println!("{output}");
            }
            value
        }
    }

    #[test]
    fn parser_parse_stream() {
        let tests = vec![
            // left
            ("2+3*4*5", true, Some(62)),    // priority high-low-high (assembly)
            ("1+2+3+4+5+6+7+8+9", true, Some(45)),  // parser stack accumulation
            ("2*3+4*5", true, Some(26)),    // priority high-low-high (assembly)
            ("2+3*4+5", true, Some(19)),    // priority low-high-low (assembly)
            ("a+2*b", true, Some(50)),
            ("a*(4+5)", true, Some(90)),
            ("1*2*3*4", true, Some(24)),
            ("1+2+3+4", true, Some(10)),
            ("(1)", true, Some(1)),
            ("((5))", true, Some(5)),
            // right
            ("2^3", true, Some(8)),
            ("4^3^2", true, Some(262144)),
            // both left and right
            ("5+3*2^8-3-2+1", true, Some(769)),
            ("5:3:2^2", true, Some(25)),
            ("5:(2^4-3*(3))", true, Some(7)),
            // undef
            ("z", true, None),
            ("5*z+y", true, None),
            // errors
            ("a*(4+5", false, None),
            ("a b", false, None),
            ("a++", false, None),
        ];
        const VERBOSE: bool = false;
        const VERBOSE_LISTENER: bool = false;
        let mut parser = build_parser();

        // The lexer provides the required stream, so this isn't necessary in a real case:
        let mut symb_table = SymbolTable::new();
        symb_table.extend_terminals(SYMBOLS_T.iter().map(|(s, ss)| (s.to_string(), ss.map(|s| s.to_string()))));
        let symbols = (0..SYMBOLS_T.len() as TokenId)
            .map(|t| (Symbol::T(t).to_str(Some(&symb_table)), t))
            .collect::<HashMap<_, _>>();
        for (test_id, (input, expected_success, expected_result)) in tests.into_iter().enumerate() {
            if VERBOSE { println!("{:=<80}\ninput '{input}'", ""); }
            let stream = input.chars().into_iter().index_start::<CaretCol>(1).filter_map(|(i, c)| {
                if c.is_ascii_whitespace() {
                    None
                } else {
                    let c_str = c.to_string();
                    Some(match c {
                        '0'..='9' => (6, c_str, 1, i),
                        'a'..='z' => (7, c_str, 1, i),
                        _ => {
                            if let Some(s) = symbols.get(&c_str) {
                                // println!("stream: '{}' -> sym!({})", c, symbol_to_macro(s));
                                (*s, c_str, 1, i)
                            } else {
                                panic!("unrecognized test input '{c}' in test {test_id}, input {input}");
                            }
                        }
                    })
                }
            });

            // User code under test ------------------------------

            let mut listener = TestListener::new(VERBOSE_LISTENER);
            listener.vars.extend([
                ("a".to_string(), 10),
                ("b".to_string(), 20),
                ("c".to_string(), 30),
            ]);
            let mut wrapper = Wrapper::new(listener, VERBOSE_LISTENER);
            let success = match parser.parse_stream(&mut wrapper, stream) {
                Ok(_) => {
                    if VERBOSE { println!("parsing completed successfully"); }
                    true
                }
                Err(e) => {
                    if VERBOSE { println!("parsing failed: {e}"); }
                    false
                }
            };
            if VERBOSE {
                let msg = wrapper.listener.log.get_messages().map(|s| format!("- {s:?}")).join("\n");
                if !msg.is_empty() {
                    println!("Messages:\n{msg}");
                }
                println!("max stack: {}\nmax asm_stack: {}", wrapper.max_stack, wrapper.max_asm_stack);
                println!("listener stack: {:?}", wrapper.stack);
                println!("listener asm_stack: {:?}", wrapper.asm_stack);
            }
            let listener = wrapper.listener();
            // ---------------------------------------------------

            assert_eq!(success, expected_success, "test {test_id} failed for input {input}");
            if VERBOSE { println!("listener data: {:?}", listener.result); }
            if success {
                assert_eq!(listener.result, expected_result, "test {test_id} failed for input {input}");
            }
        }
    }
}

#[allow(unused)]
mod listener3 {
    // -------------------------------------------------------------------------
    // [write_source_code_for_integration_listener3]

    use lexigram::{grammar::{FactorId, ProdFactor, Symbol, VarId}, parser::{OpCode, Parser}, symbol_table::SymbolTable};

    const PARSER_NUM_T: usize = 6;
    const PARSER_NUM_NT: usize = 2;
    const SYMBOLS_T: [(&str, Option<&str>); PARSER_NUM_T] = [("struct", Some("struct")), ("{", Some("{")), ("}", Some("}")), (":", Some(":")), (";", Some(";")), ("id", None)];
    const SYMBOLS_NT: [&str; PARSER_NUM_NT] = ["STRUCT", "LIST"];
    const PARSING_FACTORS: [(VarId, &[Symbol]); 3] = [(0, &[Symbol::T(0), Symbol::T(5), Symbol::T(1), Symbol::NT(1)]), (1, &[Symbol::T(5), Symbol::T(3), Symbol::T(5), Symbol::T(4), Symbol::NT(1)]), (1, &[Symbol::T(2)])];
    const PARSING_TABLE: [FactorId; 14] = [0, 3, 3, 3, 3, 3, 4, 3, 3, 2, 3, 3, 1, 4];
    const FLAGS: [u32; 2] = [0, 2];
    const PARENT: [Option<VarId>; 2] = [None, None];
    const OPCODES: [&[OpCode]; 3] = [&[OpCode::Exit(0), OpCode::NT(1), OpCode::T(1), OpCode::T(5), OpCode::T(0)], &[OpCode::Exit(1), OpCode::NT(1), OpCode::T(4), OpCode::T(5), OpCode::T(3), OpCode::T(5)], &[OpCode::Exit(2), OpCode::T(2)]];
    const START_SYMBOL: VarId = 0;

    pub fn build_parser() -> Parser {
        let mut symbol_table = SymbolTable::new();
        symbol_table.extend_terminals(SYMBOLS_T.into_iter().map(|(s, os)| (s.to_string(), os.map(|s| s.to_string()))));
        symbol_table.extend_non_terminals(SYMBOLS_NT.into_iter().map(|s| s.to_string()));
        let factors: Vec<(VarId, ProdFactor)> = PARSING_FACTORS.into_iter().map(|(v, s)| (v, ProdFactor::new(s.to_vec()))).collect();
        let table: Vec<FactorId> = PARSING_TABLE.into();
        let parsing_table = lexigram::grammar::LLParsingTable {
            num_nt: PARSER_NUM_NT,
            num_t: PARSER_NUM_T + 1,
            factors,
            table,
            flags: FLAGS.into(),
            parent: PARENT.into(),
        };
        Parser::new(parsing_table, symbol_table, OPCODES.into_iter().map(|strip| strip.to_vec()).collect(), START_SYMBOL)
    }

    // [write_source_code_for_integration_listener3]
    // -------------------------------------------------------------------------
}

#[allow(unused)]
mod listener4 {
    // -------------------------------------------------------------------------
    // [write_source_code_for_integration_listener4]

    use lexigram::{grammar::{FactorId, ProdFactor, Symbol, VarId}, parser::{OpCode, Parser}, symbol_table::SymbolTable};

    const PARSER_NUM_T: usize = 6;
    const PARSER_NUM_NT: usize = 2;
    const SYMBOLS_T: [(&str, Option<&str>); PARSER_NUM_T] = [("struct", Some("struct")), ("{", Some("{")), ("}", Some("}")), (":", Some(":")), (";", Some(";")), ("id", None)];
    const SYMBOLS_NT: [&str; PARSER_NUM_NT] = ["STRUCT", "LIST"];
    const PARSING_FACTORS: [(VarId, &[Symbol]); 3] = [(0, &[Symbol::T(0), Symbol::T(5), Symbol::T(1), Symbol::NT(1)]), (1, &[Symbol::T(5), Symbol::T(3), Symbol::T(5), Symbol::T(4), Symbol::NT(1)]), (1, &[Symbol::T(2)])];
    const PARSING_TABLE: [FactorId; 14] = [0, 3, 3, 3, 3, 3, 4, 3, 3, 2, 3, 3, 1, 4];
    const FLAGS: [u32; 2] = [0, 130];
    const PARENT: [Option<VarId>; 2] = [None, None];
    const OPCODES: [&[OpCode]; 3] = [&[OpCode::Exit(0), OpCode::NT(1), OpCode::T(1), OpCode::T(5), OpCode::T(0)], &[OpCode::Loop(1), OpCode::Exit(1), OpCode::T(4), OpCode::T(5), OpCode::T(3), OpCode::T(5)], &[OpCode::Exit(2), OpCode::T(2)]];
    const START_SYMBOL: VarId = 0;

    pub fn build_parser() -> Parser {
        let mut symbol_table = SymbolTable::new();
        symbol_table.extend_terminals(SYMBOLS_T.into_iter().map(|(s, os)| (s.to_string(), os.map(|s| s.to_string()))));
        symbol_table.extend_non_terminals(SYMBOLS_NT.into_iter().map(|s| s.to_string()));
        let factors: Vec<(VarId, ProdFactor)> = PARSING_FACTORS.into_iter().map(|(v, s)| (v, ProdFactor::new(s.to_vec()))).collect();
        let table: Vec<FactorId> = PARSING_TABLE.into();
        let parsing_table = lexigram::grammar::LLParsingTable {
            num_nt: PARSER_NUM_NT,
            num_t: PARSER_NUM_T + 1,
            factors,
            table,
            flags: FLAGS.into(),
            parent: PARENT.into(),
        };
        Parser::new(parsing_table, symbol_table, OPCODES.into_iter().map(|strip| strip.to_vec()).collect(), START_SYMBOL)
    }

    // [write_source_code_for_integration_listener4]
    // -------------------------------------------------------------------------
}

#[allow(unused)]
mod listener5 {
    // -------------------------------------------------------------------------
    // [write_source_code_for_integration_listener5]

    use lexigram::{grammar::{FactorId, ProdFactor, Symbol, VarId}, parser::{OpCode, Parser}, symbol_table::SymbolTable};

    const PARSER_NUM_T: usize = 2;
    const PARSER_NUM_NT: usize = 3;
    const SYMBOLS_T: [(&str, Option<&str>); PARSER_NUM_T] = [(".", Some(".")), ("id", None)];
    const SYMBOLS_NT: [&str; PARSER_NUM_NT] = ["E", "F", "E_1"];
    const PARSING_FACTORS: [(VarId, &[Symbol]); 4] = [(0, &[Symbol::NT(1), Symbol::NT(2)]), (1, &[Symbol::T(1)]), (2, &[Symbol::T(0), Symbol::T(1), Symbol::NT(2)]), (2, &[Symbol::Empty])];
    const PARSING_TABLE: [FactorId; 9] = [4, 0, 5, 5, 1, 5, 2, 4, 3];
    const FLAGS: [u32; 3] = [512, 0, 4];
    const PARENT: [Option<VarId>; 3] = [None, None, Some(0)];
    const OPCODES: [&[OpCode]; 4] = [&[OpCode::NT(2), OpCode::Exit(0), OpCode::NT(1)], &[OpCode::Exit(1), OpCode::T(1)], &[OpCode::Loop(2), OpCode::Exit(2), OpCode::T(1), OpCode::T(0)], &[OpCode::Exit(3)]];
    const START_SYMBOL: VarId = 0;

    pub fn build_parser() -> Parser {
        let mut symbol_table = SymbolTable::new();
        symbol_table.extend_terminals(SYMBOLS_T.into_iter().map(|(s, os)| (s.to_string(), os.map(|s| s.to_string()))));
        symbol_table.extend_non_terminals(SYMBOLS_NT.into_iter().map(|s| s.to_string()));
        let factors: Vec<(VarId, ProdFactor)> = PARSING_FACTORS.into_iter().map(|(v, s)| (v, ProdFactor::new(s.to_vec()))).collect();
        let table: Vec<FactorId> = PARSING_TABLE.into();
        let parsing_table = lexigram::grammar::LLParsingTable {
            num_nt: PARSER_NUM_NT,
            num_t: PARSER_NUM_T + 1,
            factors,
            table,
            flags: FLAGS.into(),
            parent: PARENT.into(),
        };
        Parser::new(parsing_table, symbol_table, OPCODES.into_iter().map(|strip| strip.to_vec()).collect(), START_SYMBOL)
    }

    // [write_source_code_for_integration_listener5]
    // -------------------------------------------------------------------------
}

#[allow(unused)]
mod listener6 {
    // -------------------------------------------------------------------------
    // [write_source_code_for_integration_listener6]

    use lexigram::{grammar::{FactorId, ProdFactor, Symbol, VarId}, parser::{OpCode, Parser}, symbol_table::SymbolTable};

    const PARSER_NUM_T: usize = 4;
    const PARSER_NUM_NT: usize = 4;
    const SYMBOLS_T: [(&str, Option<&str>); PARSER_NUM_T] = [(".", Some(".")), ("id", None), ("(", Some("(")), (")", Some(")"))];
    const SYMBOLS_NT: [&str; PARSER_NUM_NT] = ["E", "F", "E_1", "E_2"];
    const PARSING_FACTORS: [(VarId, &[Symbol]); 6] = [(0, &[Symbol::NT(1), Symbol::NT(2)]), (1, &[Symbol::T(1)]), (2, &[Symbol::T(0), Symbol::T(1), Symbol::NT(3)]), (2, &[Symbol::Empty]), (3, &[Symbol::T(2), Symbol::T(3), Symbol::NT(2)]), (3, &[Symbol::NT(2)])];
    const PARSING_TABLE: [FactorId; 20] = [6, 0, 6, 6, 7, 7, 1, 6, 6, 7, 2, 6, 6, 6, 3, 5, 6, 4, 6, 5];
    const FLAGS: [u32; 4] = [512, 0, 36, 64];
    const PARENT: [Option<VarId>; 4] = [None, None, Some(0), Some(2)];
    const OPCODES: [&[OpCode]; 6] = [&[OpCode::NT(2), OpCode::Exit(0), OpCode::NT(1)], &[OpCode::Exit(1), OpCode::T(1)], &[OpCode::NT(3), OpCode::T(1), OpCode::T(0)], &[OpCode::Exit(3)], &[OpCode::Loop(2), OpCode::Exit(4), OpCode::T(3), OpCode::T(2)], &[OpCode::Loop(2), OpCode::Exit(5)]];
    const START_SYMBOL: VarId = 0;

    pub fn build_parser() -> Parser {
        let mut symbol_table = SymbolTable::new();
        symbol_table.extend_terminals(SYMBOLS_T.into_iter().map(|(s, os)| (s.to_string(), os.map(|s| s.to_string()))));
        symbol_table.extend_non_terminals(SYMBOLS_NT.into_iter().map(|s| s.to_string()));
        let factors: Vec<(VarId, ProdFactor)> = PARSING_FACTORS.into_iter().map(|(v, s)| (v, ProdFactor::new(s.to_vec()))).collect();
        let table: Vec<FactorId> = PARSING_TABLE.into();
        let parsing_table = lexigram::grammar::LLParsingTable {
            num_nt: PARSER_NUM_NT,
            num_t: PARSER_NUM_T + 1,
            factors,
            table,
            flags: FLAGS.into(),
            parent: PARENT.into(),
        };
        Parser::new(parsing_table, symbol_table, OPCODES.into_iter().map(|strip| strip.to_vec()).collect(), START_SYMBOL)
    }

    // [write_source_code_for_integration_listener6]
    // -------------------------------------------------------------------------
}

#[allow(unused)]
mod listener7 {
    // -------------------------------------------------------------------------
    // [write_source_code_for_integration_listener7]

    use lexigram::{grammar::{FactorId, ProdFactor, Symbol, VarId}, parser::{OpCode, Parser}, symbol_table::SymbolTable};

    const PARSER_NUM_T: usize = 3;
    const PARSER_NUM_NT: usize = 2;
    const SYMBOLS_T: [(&str, Option<&str>); PARSER_NUM_T] = [("a", None), ("b", None), ("c", None)];
    const SYMBOLS_NT: [&str; PARSER_NUM_NT] = ["A", "A_1"];
    const PARSING_FACTORS: [(VarId, &[Symbol]); 3] = [(0, &[Symbol::T(0), Symbol::NT(1), Symbol::T(2)]), (1, &[Symbol::T(1), Symbol::NT(1)]), (1, &[Symbol::Empty])];
    const PARSING_TABLE: [FactorId; 8] = [0, 3, 3, 4, 3, 1, 2, 3];
    const FLAGS: [u32; 2] = [2048, 1];
    const PARENT: [Option<VarId>; 2] = [None, Some(0)];
    const OPCODES: [&[OpCode]; 3] = [&[OpCode::Exit(0), OpCode::T(2), OpCode::NT(1), OpCode::T(0)], &[OpCode::Loop(1), OpCode::Exit(1), OpCode::T(1)], &[OpCode::Exit(2)]];
    const START_SYMBOL: VarId = 0;

    pub fn build_parser() -> Parser {
        let mut symbol_table = SymbolTable::new();
        symbol_table.extend_terminals(SYMBOLS_T.into_iter().map(|(s, os)| (s.to_string(), os.map(|s| s.to_string()))));
        symbol_table.extend_non_terminals(SYMBOLS_NT.into_iter().map(|s| s.to_string()));
        let factors: Vec<(VarId, ProdFactor)> = PARSING_FACTORS.into_iter().map(|(v, s)| (v, ProdFactor::new(s.to_vec()))).collect();
        let table: Vec<FactorId> = PARSING_TABLE.into();
        let parsing_table = lexigram::grammar::LLParsingTable {
            num_nt: PARSER_NUM_NT,
            num_t: PARSER_NUM_T + 1,
            factors,
            table,
            flags: FLAGS.into(),
            parent: PARENT.into(),
        };
        Parser::new(parsing_table, symbol_table, OPCODES.into_iter().map(|strip| strip.to_vec()).collect(), START_SYMBOL)
    }

    // [write_source_code_for_integration_listener7]
    // -------------------------------------------------------------------------
}

#[allow(unused)]
mod listener8 {
    // -------------------------------------------------------------------------
    // [write_source_code_for_integration_listener8]

    use lexigram::{grammar::{FactorId, ProdFactor, Symbol, VarId}, parser::{OpCode, Parser}, symbol_table::SymbolTable};

    const PARSER_NUM_T: usize = 3;
    const PARSER_NUM_NT: usize = 2;
    const SYMBOLS_T: [(&str, Option<&str>); PARSER_NUM_T] = [("a", None), ("b", None), ("c", None)];
    const SYMBOLS_NT: [&str; PARSER_NUM_NT] = ["A", "AIter1"];
    const PARSING_FACTORS: [(VarId, &[Symbol]); 3] = [(0, &[Symbol::T(0), Symbol::NT(1), Symbol::T(2)]), (1, &[Symbol::T(1), Symbol::NT(1)]), (1, &[Symbol::Empty])];
    const PARSING_TABLE: [FactorId; 8] = [0, 3, 3, 4, 3, 1, 2, 3];
    const FLAGS: [u32; 2] = [2048, 129];
    const PARENT: [Option<VarId>; 2] = [None, Some(0)];
    const OPCODES: [&[OpCode]; 3] = [&[OpCode::Exit(0), OpCode::T(2), OpCode::NT(1), OpCode::T(0)], &[OpCode::Loop(1), OpCode::Exit(1), OpCode::T(1)], &[OpCode::Exit(2)]];
    const START_SYMBOL: VarId = 0;

    pub fn build_parser() -> Parser {
        let mut symbol_table = SymbolTable::new();
        symbol_table.extend_terminals(SYMBOLS_T.into_iter().map(|(s, os)| (s.to_string(), os.map(|s| s.to_string()))));
        symbol_table.extend_non_terminals(SYMBOLS_NT.into_iter().map(|s| s.to_string()));
        let factors: Vec<(VarId, ProdFactor)> = PARSING_FACTORS.into_iter().map(|(v, s)| (v, ProdFactor::new(s.to_vec()))).collect();
        let table: Vec<FactorId> = PARSING_TABLE.into();
        let parsing_table = lexigram::grammar::LLParsingTable {
            num_nt: PARSER_NUM_NT,
            num_t: PARSER_NUM_T + 1,
            factors,
            table,
            flags: FLAGS.into(),
            parent: PARENT.into(),
        };
        Parser::new(parsing_table, symbol_table, OPCODES.into_iter().map(|strip| strip.to_vec()).collect(), START_SYMBOL)
    }

    // [write_source_code_for_integration_listener8]
    // -------------------------------------------------------------------------
}

#[allow(unused)]
mod listener9 {
    // -------------------------------------------------------------------------
    // [write_source_code_for_integration_listener9]

    use lexigram::{grammar::{FactorId, ProdFactor, Symbol, VarId}, parser::{OpCode, Parser}, symbol_table::SymbolTable};

    const PARSER_NUM_T: usize = 3;
    const PARSER_NUM_NT: usize = 4;
    const SYMBOLS_T: [(&str, Option<&str>); PARSER_NUM_T] = [("a", None), ("b", None), ("c", None)];
    const SYMBOLS_NT: [&str; PARSER_NUM_NT] = ["A", "A_1", "A_2", "A_3"];
    const PARSING_FACTORS: [(VarId, &[Symbol]); 6] = [(0, &[Symbol::T(0), Symbol::NT(2)]), (1, &[Symbol::T(2), Symbol::NT(3)]), (2, &[Symbol::NT(1), Symbol::T(1), Symbol::NT(2)]), (2, &[Symbol::Empty]), (3, &[Symbol::NT(1)]), (3, &[Symbol::Empty])];
    const PARSING_TABLE: [FactorId; 16] = [0, 6, 6, 7, 6, 7, 1, 6, 6, 6, 2, 3, 6, 5, 4, 6];
    const FLAGS: [u32; 4] = [6656, 4129, 4, 64];
    const PARENT: [Option<VarId>; 4] = [None, Some(0), Some(0), Some(1)];
    const OPCODES: [&[OpCode]; 6] = [&[OpCode::NT(2), OpCode::Exit(0), OpCode::T(0)], &[OpCode::NT(3), OpCode::T(2)], &[OpCode::Loop(2), OpCode::Exit(2), OpCode::T(1), OpCode::NT(1)], &[OpCode::Exit(3)], &[OpCode::Loop(1), OpCode::Exit(4)], &[OpCode::Exit(5)]];
    const START_SYMBOL: VarId = 0;

    pub fn build_parser() -> Parser {
        let mut symbol_table = SymbolTable::new();
        symbol_table.extend_terminals(SYMBOLS_T.into_iter().map(|(s, os)| (s.to_string(), os.map(|s| s.to_string()))));
        symbol_table.extend_non_terminals(SYMBOLS_NT.into_iter().map(|s| s.to_string()));
        let factors: Vec<(VarId, ProdFactor)> = PARSING_FACTORS.into_iter().map(|(v, s)| (v, ProdFactor::new(s.to_vec()))).collect();
        let table: Vec<FactorId> = PARSING_TABLE.into();
        let parsing_table = lexigram::grammar::LLParsingTable {
            num_nt: PARSER_NUM_NT,
            num_t: PARSER_NUM_T + 1,
            factors,
            table,
            flags: FLAGS.into(),
            parent: PARENT.into(),
        };
        Parser::new(parsing_table, symbol_table, OPCODES.into_iter().map(|strip| strip.to_vec()).collect(), START_SYMBOL)
    }

    // [write_source_code_for_integration_listener9]
    // -------------------------------------------------------------------------
}

#[allow(unused)]
mod listener10 {
    // -------------------------------------------------------------------------
    // [write_source_code_for_integration_listener10]

    use lexigram::{grammar::{FactorId, ProdFactor, Symbol, VarId}, parser::{OpCode, Parser}, symbol_table::SymbolTable};

    const PARSER_NUM_T: usize = 3;
    const PARSER_NUM_NT: usize = 3;
    const SYMBOLS_T: [(&str, Option<&str>); PARSER_NUM_T] = [("a", None), ("b", None), ("c", None)];
    const SYMBOLS_NT: [&str; PARSER_NUM_NT] = ["A", "A_1", "A_2"];
    const PARSING_FACTORS: [(VarId, &[Symbol]); 4] = [(0, &[Symbol::T(0), Symbol::NT(1), Symbol::T(2)]), (1, &[Symbol::T(1), Symbol::NT(2)]), (2, &[Symbol::NT(1)]), (2, &[Symbol::Empty])];
    const PARSING_TABLE: [FactorId; 12] = [0, 4, 4, 5, 4, 1, 5, 4, 4, 2, 3, 4];
    const FLAGS: [u32; 3] = [6144, 4129, 64];
    const PARENT: [Option<VarId>; 3] = [None, Some(0), Some(1)];
    const OPCODES: [&[OpCode]; 4] = [&[OpCode::Exit(0), OpCode::T(2), OpCode::NT(1), OpCode::T(0)], &[OpCode::NT(2), OpCode::T(1)], &[OpCode::Loop(1), OpCode::Exit(2)], &[OpCode::Exit(3)]];
    const START_SYMBOL: VarId = 0;

    pub fn build_parser() -> Parser {
        let mut symbol_table = SymbolTable::new();
        symbol_table.extend_terminals(SYMBOLS_T.into_iter().map(|(s, os)| (s.to_string(), os.map(|s| s.to_string()))));
        symbol_table.extend_non_terminals(SYMBOLS_NT.into_iter().map(|s| s.to_string()));
        let factors: Vec<(VarId, ProdFactor)> = PARSING_FACTORS.into_iter().map(|(v, s)| (v, ProdFactor::new(s.to_vec()))).collect();
        let table: Vec<FactorId> = PARSING_TABLE.into();
        let parsing_table = lexigram::grammar::LLParsingTable {
            num_nt: PARSER_NUM_NT,
            num_t: PARSER_NUM_T + 1,
            factors,
            table,
            flags: FLAGS.into(),
            parent: PARENT.into(),
        };
        Parser::new(parsing_table, symbol_table, OPCODES.into_iter().map(|strip| strip.to_vec()).collect(), START_SYMBOL)
    }

    // [write_source_code_for_integration_listener10]
    // -------------------------------------------------------------------------
}

#[allow(unused)]
mod listener11 {
    // -------------------------------------------------------------------------
    // [write_source_code_for_integration_listener11]

    use lexigram::{grammar::{FactorId, ProdFactor, Symbol, VarId}, parser::{OpCode, Parser}, symbol_table::SymbolTable};

    const PARSER_NUM_T: usize = 3;
    const PARSER_NUM_NT: usize = 4;
    const SYMBOLS_T: [(&str, Option<&str>); PARSER_NUM_T] = [("a", None), ("b", None), ("c", None)];
    const SYMBOLS_NT: [&str; PARSER_NUM_NT] = ["A", "B", "A_1", "A_2"];
    const PARSING_FACTORS: [(VarId, &[Symbol]); 5] = [(0, &[Symbol::T(0), Symbol::NT(2), Symbol::T(2)]), (1, &[Symbol::T(1)]), (2, &[Symbol::NT(1), Symbol::NT(3)]), (3, &[Symbol::NT(2)]), (3, &[Symbol::Empty])];
    const PARSING_TABLE: [FactorId; 16] = [0, 5, 5, 6, 5, 1, 6, 5, 5, 2, 6, 5, 5, 3, 4, 5];
    const FLAGS: [u32; 4] = [6144, 0, 4129, 64];
    const PARENT: [Option<VarId>; 4] = [None, None, Some(0), Some(2)];
    const OPCODES: [&[OpCode]; 5] = [&[OpCode::Exit(0), OpCode::T(2), OpCode::NT(2), OpCode::T(0)], &[OpCode::Exit(1), OpCode::T(1)], &[OpCode::NT(3), OpCode::NT(1)], &[OpCode::Loop(2), OpCode::Exit(3)], &[OpCode::Exit(4)]];
    const START_SYMBOL: VarId = 0;

    pub fn build_parser() -> Parser {
        let mut symbol_table = SymbolTable::new();
        symbol_table.extend_terminals(SYMBOLS_T.into_iter().map(|(s, os)| (s.to_string(), os.map(|s| s.to_string()))));
        symbol_table.extend_non_terminals(SYMBOLS_NT.into_iter().map(|s| s.to_string()));
        let factors: Vec<(VarId, ProdFactor)> = PARSING_FACTORS.into_iter().map(|(v, s)| (v, ProdFactor::new(s.to_vec()))).collect();
        let table: Vec<FactorId> = PARSING_TABLE.into();
        let parsing_table = lexigram::grammar::LLParsingTable {
            num_nt: PARSER_NUM_NT,
            num_t: PARSER_NUM_T + 1,
            factors,
            table,
            flags: FLAGS.into(),
            parent: PARENT.into(),
        };
        Parser::new(parsing_table, symbol_table, OPCODES.into_iter().map(|strip| strip.to_vec()).collect(), START_SYMBOL)
    }

    // [write_source_code_for_integration_listener11]
    // -------------------------------------------------------------------------
}

#[allow(unused)]
mod listener12 {
    // -------------------------------------------------------------------------
    // [write_source_code_for_integration_listener12]

    use lexigram::{grammar::{FactorId, ProdFactor, Symbol, VarId}, parser::{OpCode, Parser}, symbol_table::SymbolTable};

    const PARSER_NUM_T: usize = 4;
    const PARSER_NUM_NT: usize = 3;
    const SYMBOLS_T: [(&str, Option<&str>); PARSER_NUM_T] = [("a", None), ("b", None), ("c", None), ("d", None)];
    const SYMBOLS_NT: [&str; PARSER_NUM_NT] = ["A", "A_1", "A_2"];
    const PARSING_FACTORS: [(VarId, &[Symbol]); 5] = [(0, &[Symbol::T(1), Symbol::NT(2)]), (1, &[Symbol::T(0), Symbol::NT(1)]), (1, &[Symbol::Empty]), (2, &[Symbol::T(2), Symbol::NT(1)]), (2, &[Symbol::T(3), Symbol::NT(1)])];
    const PARSING_TABLE: [FactorId; 15] = [5, 0, 5, 5, 6, 1, 5, 5, 5, 2, 5, 5, 3, 4, 6];
    const FLAGS: [u32; 3] = [544, 4, 64];
    const PARENT: [Option<VarId>; 3] = [None, Some(0), Some(0)];
    const OPCODES: [&[OpCode]; 5] = [&[OpCode::NT(2), OpCode::T(1)], &[OpCode::Loop(1), OpCode::Exit(1), OpCode::T(0)], &[OpCode::Exit(2)], &[OpCode::NT(1), OpCode::Exit(3), OpCode::T(2)], &[OpCode::NT(1), OpCode::Exit(4), OpCode::T(3)]];
    const START_SYMBOL: VarId = 0;

    pub fn build_parser() -> Parser {
        let mut symbol_table = SymbolTable::new();
        symbol_table.extend_terminals(SYMBOLS_T.into_iter().map(|(s, os)| (s.to_string(), os.map(|s| s.to_string()))));
        symbol_table.extend_non_terminals(SYMBOLS_NT.into_iter().map(|s| s.to_string()));
        let factors: Vec<(VarId, ProdFactor)> = PARSING_FACTORS.into_iter().map(|(v, s)| (v, ProdFactor::new(s.to_vec()))).collect();
        let table: Vec<FactorId> = PARSING_TABLE.into();
        let parsing_table = lexigram::grammar::LLParsingTable {
            num_nt: PARSER_NUM_NT,
            num_t: PARSER_NUM_T + 1,
            factors,
            table,
            flags: FLAGS.into(),
            parent: PARENT.into(),
        };
        Parser::new(parsing_table, symbol_table, OPCODES.into_iter().map(|strip| strip.to_vec()).collect(), START_SYMBOL)
    }

    // [write_source_code_for_integration_listener12]
    // -------------------------------------------------------------------------
}

#[allow(unused)]
mod listener13 {
    // -------------------------------------------------------------------------
    // [write_source_code_for_integration_listener13]

    use lexigram::{grammar::{FactorId, ProdFactor, Symbol, VarId}, parser::{OpCode, Parser}, symbol_table::SymbolTable};

    const PARSER_NUM_T: usize = 3;
    const PARSER_NUM_NT: usize = 3;
    const SYMBOLS_T: [(&str, Option<&str>); PARSER_NUM_T] = [(".", Some(".")), ("id", None), ("num", None)];
    const SYMBOLS_NT: [&str; PARSER_NUM_NT] = ["E", "F", "E_1"];
    const PARSING_FACTORS: [(VarId, &[Symbol]); 5] = [(0, &[Symbol::NT(1), Symbol::NT(2)]), (0, &[Symbol::T(2), Symbol::NT(2)]), (1, &[Symbol::T(1)]), (2, &[Symbol::T(0), Symbol::T(1), Symbol::NT(2)]), (2, &[Symbol::Empty])];
    const PARSING_TABLE: [FactorId; 12] = [5, 0, 1, 6, 6, 2, 5, 6, 3, 5, 5, 4];
    const FLAGS: [u32; 3] = [512, 0, 4];
    const PARENT: [Option<VarId>; 3] = [None, None, Some(0)];
    const OPCODES: [&[OpCode]; 5] = [&[OpCode::NT(2), OpCode::Exit(0), OpCode::NT(1)], &[OpCode::NT(2), OpCode::Exit(1), OpCode::T(2)], &[OpCode::Exit(2), OpCode::T(1)], &[OpCode::Loop(2), OpCode::Exit(3), OpCode::T(1), OpCode::T(0)], &[OpCode::Exit(4)]];
    const START_SYMBOL: VarId = 0;

    pub fn build_parser() -> Parser {
        let mut symbol_table = SymbolTable::new();
        symbol_table.extend_terminals(SYMBOLS_T.into_iter().map(|(s, os)| (s.to_string(), os.map(|s| s.to_string()))));
        symbol_table.extend_non_terminals(SYMBOLS_NT.into_iter().map(|s| s.to_string()));
        let factors: Vec<(VarId, ProdFactor)> = PARSING_FACTORS.into_iter().map(|(v, s)| (v, ProdFactor::new(s.to_vec()))).collect();
        let table: Vec<FactorId> = PARSING_TABLE.into();
        let parsing_table = lexigram::grammar::LLParsingTable {
            num_nt: PARSER_NUM_NT,
            num_t: PARSER_NUM_T + 1,
            factors,
            table,
            flags: FLAGS.into(),
            parent: PARENT.into(),
        };
        Parser::new(parsing_table, symbol_table, OPCODES.into_iter().map(|strip| strip.to_vec()).collect(), START_SYMBOL)
    }

    // [write_source_code_for_integration_listener13]
    // -------------------------------------------------------------------------
}

#[allow(unused)]
pub(crate) mod listener14 {
    // -------------------------------------------------------------------------
    // [write_source_code_for_integration_listener14]

    use lexigram::{grammar::{FactorId, ProdFactor, Symbol, VarId}, parser::{OpCode, Parser}, symbol_table::SymbolTable};

    const PARSER_NUM_T: usize = 5;
    const PARSER_NUM_NT: usize = 7;
    const SYMBOLS_T: [(&str, Option<&str>); PARSER_NUM_T] = [("EXP", Some("^")), ("MUL", Some("*")), ("NEG", Some("-")), ("ADD", Some("+")), ("ID", None)];
    const SYMBOLS_NT: [&str; PARSER_NUM_NT] = ["E", "E3", "E5", "E6", "E_1", "E3_1", "E5_1"];
    const PARSING_FACTORS: [(VarId, &[Symbol]); 14] = [(0, &[Symbol::NT(3), Symbol::NT(4)]), (1, &[Symbol::NT(3), Symbol::NT(5)]), (2, &[Symbol::NT(3), Symbol::NT(6)]), (3, &[Symbol::T(2), Symbol::NT(1)]), (3, &[Symbol::T(4)]), (4, &[Symbol::T(0), Symbol::NT(2), Symbol::NT(4)]), (4, &[Symbol::T(1), Symbol::NT(2), Symbol::NT(4)]), (4, &[Symbol::T(3), Symbol::NT(1), Symbol::NT(4)]), (4, &[Symbol::Empty]), (5, &[Symbol::T(0), Symbol::NT(2), Symbol::NT(5)]), (5, &[Symbol::T(1), Symbol::NT(2), Symbol::NT(5)]), (5, &[Symbol::Empty]), (6, &[Symbol::T(0), Symbol::NT(2)]), (6, &[Symbol::Empty])];
    const PARSING_TABLE: [FactorId; 42] = [14, 14, 0, 14, 0, 15, 15, 15, 1, 15, 1, 15, 15, 15, 2, 15, 2, 15, 15, 15, 3, 15, 4, 15, 5, 6, 14, 7, 14, 8, 9, 10, 14, 11, 14, 11, 12, 13, 14, 13, 14, 13];
    const FLAGS: [u32; 7] = [512, 512, 34, 0, 4, 4, 64];
    const PARENT: [Option<VarId>; 7] = [None, None, None, None, Some(0), Some(1), Some(2)];
    const OPCODES: [&[OpCode]; 14] = [&[OpCode::NT(4), OpCode::Exit(0), OpCode::NT(3)], &[OpCode::NT(5), OpCode::Exit(1), OpCode::NT(3)], &[OpCode::NT(6), OpCode::NT(3)], &[OpCode::Exit(3), OpCode::NT(1), OpCode::T(2)], &[OpCode::Exit(4), OpCode::T(4)], &[OpCode::Loop(4), OpCode::Exit(5), OpCode::NT(2), OpCode::T(0)], &[OpCode::Loop(4), OpCode::Exit(6), OpCode::NT(2), OpCode::T(1)], &[OpCode::Loop(4), OpCode::Exit(7), OpCode::NT(1), OpCode::T(3)], &[OpCode::Exit(8)], &[OpCode::Loop(5), OpCode::Exit(9), OpCode::NT(2), OpCode::T(0)], &[OpCode::Loop(5), OpCode::Exit(10), OpCode::NT(2), OpCode::T(1)], &[OpCode::Exit(11)], &[OpCode::Exit(12), OpCode::NT(2), OpCode::T(0)], &[OpCode::Exit(13)]];
    const START_SYMBOL: VarId = 0;

    pub fn build_parser() -> Parser {
        let mut symbol_table = SymbolTable::new();
        symbol_table.extend_terminals(SYMBOLS_T.into_iter().map(|(s, os)| (s.to_string(), os.map(|s| s.to_string()))));
        symbol_table.extend_non_terminals(SYMBOLS_NT.into_iter().map(|s| s.to_string()));
        let factors: Vec<(VarId, ProdFactor)> = PARSING_FACTORS.into_iter().map(|(v, s)| (v, ProdFactor::new(s.to_vec()))).collect();
        let table: Vec<FactorId> = PARSING_TABLE.into();
        let parsing_table = lexigram::grammar::LLParsingTable {
            num_nt: PARSER_NUM_NT,
            num_t: PARSER_NUM_T + 1,
            factors,
            table,
            flags: FLAGS.into(),
            parent: PARENT.into(),
        };
        Parser::new(parsing_table, symbol_table, OPCODES.into_iter().map(|strip| strip.to_vec()).collect(), START_SYMBOL)
    }

    // [write_source_code_for_integration_listener14]
    // -------------------------------------------------------------------------
}