// Copyright (c) 2025 Redglyph (@gmail.com). All Rights Reserved.

#![cfg(test)]
//#![allow(non_camel_case_types)]
#![allow(dead_code)]

// Most of the code below is generated by parsergen::tests::wrapper_source::build_items.
// Some of those wrappers are tested in crate::integration::wrappers.

// ================================================================================

pub(crate) mod rules_13_1 {
    /// User-defined type for `s`
    #[derive(Debug, PartialEq)]
    pub struct SynS();
    
    /// User-defined type for `val`
    #[derive(Debug, PartialEq)]
    pub struct SynVal();
    
    // ------------------------------------------------------------
    // [wrapper source for rule 13 #1, start s]

    use lexigram_lib::{AltId, TokenId, VarId, lexer::PosSpan, log::{LogMsg, Logger}, parser::{Call, ListenerWrapper, Terminate}};

    #[derive(Debug)]
    pub enum CtxS {
        /// `s -> Id "=" val`
        V1 { id: String, val: SynVal },
        /// `s -> "exit"`
        V2,
        /// `s -> "return" val`
        V3 { val: SynVal },
    }
    #[derive(Debug)]
    pub enum CtxVal {
        /// `val -> Id`
        V1 { id: String },
        /// `val -> Num`
        V2 { num: String },
    }

    #[derive(Debug)]
    enum EnumSynValue { S(SynS), Val(SynVal) }

    impl EnumSynValue {
        fn get_s(self) -> SynS {
            if let EnumSynValue::S(val) = self { val } else { panic!() }
        }
        fn get_val(self) -> SynVal {
            if let EnumSynValue::Val(val) = self { val } else { panic!() }
        }
    }

    pub trait TestListener {
        /// Checks if the listener requests an abort. This happens if an error is too difficult to recover from
        /// and may corrupt the stack content. In that case, the parser immediately stops and returns `ParserError::AbortRequest`.
        fn check_abort_request(&self) -> Terminate { Terminate::None }
        fn get_log_mut(&mut self) -> &mut impl Logger;
        #[allow(unused_variables)]
        fn handle_msg(&mut self, span_opt: Option<&PosSpan>, msg: LogMsg) {
            self.get_log_mut().add(msg);
        }
        #[allow(unused_variables)]
        fn intercept_token(&mut self, token: TokenId, text: &str, span: &PosSpan) -> TokenId { token }
        #[allow(unused_variables)]
        fn exit(&mut self, s: SynS, span: PosSpan) {}
        #[allow(unused_variables)]
        fn abort(&mut self, terminate: Terminate) {}
        fn exit_s(&mut self, ctx: CtxS, spans: Vec<PosSpan>) -> SynS;
        fn exit_val(&mut self, ctx: CtxVal, spans: Vec<PosSpan>) -> SynVal;
    }

    pub struct Wrapper<T> {
        verbose: bool,
        listener: T,
        stack: Vec<EnumSynValue>,
        max_stack: usize,
        stack_t: Vec<String>,
        stack_span: Vec<PosSpan>,
    }

    impl<T: TestListener> ListenerWrapper for Wrapper<T> {
        fn switch(&mut self, call: Call, nt: VarId, alt_id: AltId, t_data: Option<Vec<String>>) {
            if self.verbose {
                println!("switch: call={call:?}, nt={nt}, alt={alt_id}, t_data={t_data:?}");
            }
            if let Some(mut t_data) = t_data {
                self.stack_t.append(&mut t_data);
            }
            match call {
                Call::Exit => {
                    match alt_id {
                        0 |                                         // s -> Id "=" val
                        1 |                                         // s -> "exit"
                        2 => self.exit_s(alt_id),                   // s -> "return" val
                        3 |                                         // val -> Id
                        4 => self.exit_val(alt_id),                 // val -> Num
                        _ => panic!("unexpected exit alternative id: {alt_id}")
                    }
                }
                Call::End(terminate) => {
                    match terminate {
                        Terminate::None => {
                            let val = self.stack.pop().unwrap().get_s();
                            let span = self.stack_span.pop().unwrap();
                            self.listener.exit(val, span);
                        }
                        Terminate::Abort | Terminate::Conclude => self.listener.abort(terminate),
                    }
                }
                _ => panic!("unexpected call {call:?}, nt {nt}, alt_id {alt_id}")
            }
            self.max_stack = std::cmp::max(self.max_stack, self.stack.len());
            if self.verbose {
                println!("> stack_t:   {}", self.stack_t.join(", "));
                println!("> stack:     {}", self.stack.iter().map(|it| format!("{it:?}")).collect::<Vec<_>>().join(", "));
            }
        }

        fn check_abort_request(&self) -> Terminate {
            self.listener.check_abort_request()
        }

        fn abort(&mut self) {
            self.stack.clear();
            self.stack_span.clear();
            self.stack_t.clear();
        }

        fn get_log_mut(&mut self) -> &mut impl Logger {
            self.listener.get_log_mut()
        }

        fn report(&mut self, span_opt: Option<&PosSpan>, msg: LogMsg) {
            self.listener.handle_msg(span_opt, msg);
        }

        fn push_span(&mut self, span: PosSpan) {
            self.stack_span.push(span);
        }

        fn is_stack_empty(&self) -> bool {
            self.stack.is_empty()
        }

        fn is_stack_t_empty(&self) -> bool {
            self.stack_t.is_empty()
        }

        fn is_stack_span_empty(&self) -> bool {
            self.stack_span.is_empty()
        }

        fn intercept_token(&mut self, token: TokenId, text: &str, span: &PosSpan) -> TokenId {
            self.listener.intercept_token(token, text, span)
        }
    }

    impl<T: TestListener> Wrapper<T> {
        pub fn new(listener: T, verbose: bool) -> Self {
            Wrapper { verbose, listener, stack: Vec::new(), max_stack: 0, stack_t: Vec::new(), stack_span: Vec::new() }
        }

        pub fn get_listener(&self) -> &T {
            &self.listener
        }

        pub fn get_listener_mut(&mut self) -> &mut T {
            &mut self.listener
        }

        pub fn give_listener(self) -> T {
            self.listener
        }

        pub fn set_verbose(&mut self, verbose: bool) {
            self.verbose = verbose;
        }

        fn exit_s(&mut self, alt_id: AltId) {
            let (n, ctx) = match alt_id {
                0 => {
                    let val = self.stack.pop().unwrap().get_val();
                    let id = self.stack_t.pop().unwrap();
                    (3, CtxS::V1 { id, val })
                }
                1 => {
                    (1, CtxS::V2)
                }
                2 => {
                    let val = self.stack.pop().unwrap().get_val();
                    (2, CtxS::V3 { val })
                }
                _ => panic!("unexpected alt id {alt_id} in fn exit_s")
            };
            let spans = self.stack_span.drain(self.stack_span.len() - n ..).collect::<Vec<_>>();
            self.stack_span.push(spans.iter().fold(PosSpan::empty(), |acc, sp| acc + sp));
            let val = self.listener.exit_s(ctx, spans);
            self.stack.push(EnumSynValue::S(val));
        }

        fn exit_val(&mut self, alt_id: AltId) {
            let (n, ctx) = match alt_id {
                3 => {
                    let id = self.stack_t.pop().unwrap();
                    (1, CtxVal::V1 { id })
                }
                4 => {
                    let num = self.stack_t.pop().unwrap();
                    (1, CtxVal::V2 { num })
                }
                _ => panic!("unexpected alt id {alt_id} in fn exit_val")
            };
            let spans = self.stack_span.drain(self.stack_span.len() - n ..).collect::<Vec<_>>();
            self.stack_span.push(spans.iter().fold(PosSpan::empty(), |acc, sp| acc + sp));
            let val = self.listener.exit_val(ctx, spans);
            self.stack.push(EnumSynValue::Val(val));
        }
    }

    // [wrapper source for rule 13 #1, start s]
    // ------------------------------------------------------------
}

// ================================================================================
